networks:
    dcp:
        name: dcp
        external: true

services:
    chatgpt-scraper:
        build: .
        volumes:
            - ./scripts/entrypoint.sh:/usr/src/app/entrypoint.sh
        env_file:
            - .env
        entrypoint: ["/usr/src/app/entrypoint.sh"]
        networks:
            - dcp
